entity:
  id: ip_dependency
  name: IP dependency
  key_data_type: string
  auto_create_record: true
  snapshot: true
attribs:
  flow_time_series_dep:
    name: FTS
    description: Flow Time Series
    type: timeseries
    timeseries_type: irregular_intervals
    timeseries_params:
      max_age: 365d
    series:
      packets:
        data_type: int
      bytes:
        data_type: int
      
  label:
    name: label
    descripion: Label for dependency.
    type: observations
    data_type: string
    history_params:
      pre_validity: 24h
      post_validity: 24h
      max_age: 365d
      aggregate: true

    