# MongoDB Connection configuration
db_name: "dp3_feta_ts"
username: "feta_ts"
password: "feta_ts"

# Connection parameters to Mongo cluter
connection:
  mode: "replica" 
  replica_set: feta_ts 
  hosts:
    - address: "mongo1.liberouter.org" 
      port: 27002
    - address: "mongo2.liberouter.org" 
      port: 27002
    - address: "mongo3.liberouter.org" 
      port: 27002
